import SwiftUI

/// Full-screen first-launch AI disclaimer modal.
/// Text lifted verbatim from src/components/common/AIBootDisclaimer.tsx.
///
/// Acceptance is in-memory only, for the current launch. The user may opt in to
/// "Don't show again until the next update", which persists suppression keyed to
/// the current app version+build (see `AIBootDisclaimerView.suppressedBuildKey`).
struct AIBootDisclaimerView: View {
    /// Called once the user taps "Got it", with whether "Don't show again" was toggled on.
    var onAccept: (_ dontShowAgain: Bool) -> Void

    @State private var dontShowAgain = false

    @Environment(\.openURL) private var openURL

    var body: some View {
        ZStack {
            Color.black.opacity(0.72)
                .ignoresSafeArea()

            VStack {
                Spacer()

                ScrollView {
                  VStack(alignment: .leading, spacing: 0) {
                    // Header
                    HStack(spacing: 8) {
                        Image(systemName: "brain")
                            .font(.system(size: 18, weight: .semibold))
                            .foregroundStyle(SkimStyle.accent)
                        Text("About AI in Skim")
                            .font(.system(size: 16, weight: .semibold))
                            .foregroundStyle(SkimStyle.text)
                    }
                    .padding(.bottom, 14)

                    // Body paragraphs — verbatim copy from AIBootDisclaimer.tsx
                    Group {
                        Text("Skim is a client. We do not develop, train, host, fine-tune, or operate any AI model. All AI output is generated by ")
                        + Text("third-party providers you connect using your own keys, subscription, or local install")
                            .bold()
                        + Text(" (Anthropic, OpenAI, OpenRouter, xAI, Ollama, Apple Foundation Models, llama.cpp, etc.). Skim does not run any backend; we collect no telemetry, no analytics, and no prompts or responses. Your requests go from your device directly to the provider you chose.")
                    }
                    .font(.system(size: 13, weight: .regular))
                    .foregroundStyle(SkimStyle.text)
                    .lineSpacing(3)
                    .fixedSize(horizontal: false, vertical: true)
                    .padding(.bottom, 10)

                    Group {
                        Text("We do not produce, review, curate, audit, or endorse AI output. Output may be inaccurate, biased, offensive, harmful, fabricated, or otherwise objectionable. ")
                        + Text("You alone are responsible for your prompts, provider choice, and use of the output.")
                            .bold()
                        + Text(" Your relationship is with the provider and is governed by their terms and acceptable-use policy.")
                    }
                    .font(.system(size: 13, weight: .regular))
                    .foregroundStyle(SkimStyle.text)
                    .lineSpacing(3)
                    .fixedSize(horizontal: false, vertical: true)
                    .padding(.bottom, 10)

                    Text("Skim is provided AS IS, without warranties of any kind. To the maximum extent permitted by law, Skim and its developer disclaim all liability for AI-generated content and any consequences of its use.")
                        .font(.system(size: 12, weight: .regular))
                        .foregroundStyle(SkimStyle.secondary)
                        .lineSpacing(3)
                        .fixedSize(horizontal: false, vertical: true)
                        .padding(.bottom, 10)

                    Text("By tapping Got it you accept the terms below.")
                    .font(.system(size: 13, weight: .regular))
                    .foregroundStyle(SkimStyle.text)
                    .lineSpacing(3)
                    .fixedSize(horizontal: false, vertical: true)
                    .padding(.bottom, 4)

                    HStack(spacing: 14) {
                        Button("Terms") {
                            openURL(URL(string: "https://gm2211.github.io/skim/terms.html")!)
                        }
                        .font(.system(size: 12, weight: .semibold))
                        .foregroundStyle(SkimStyle.accent)
                        .buttonStyle(.plain)

                        Button("Privacy Policy") {
                            openURL(URL(string: "https://gm2211.github.io/skim/privacy.html")!)
                        }
                        .font(.system(size: 12, weight: .semibold))
                        .foregroundStyle(SkimStyle.accent)
                        .buttonStyle(.plain)
                    }
                    .padding(.bottom, 18)

                    Divider()
                        .overlay(SkimStyle.separator)
                        .padding(.bottom, 14)

                    VStack(alignment: .leading, spacing: 14) {
                        Toggle(isOn: $dontShowAgain) {
                            Text("Don't show again until the next update")
                                .font(.system(size: 13))
                                .foregroundStyle(SkimStyle.secondary)
                        }
                        .toggleStyle(.switch)
                        .tint(SkimStyle.accent)

                        HStack {
                            Spacer()
                            Button(action: { onAccept(dontShowAgain) }) {
                                Text("Got it")
                                    .font(.system(size: 15, weight: .semibold))
                                    .foregroundStyle(.white)
                                    .padding(.horizontal, 22)
                                    .padding(.vertical, 12)
                                    .background(SkimStyle.accent, in: RoundedRectangle(cornerRadius: 14, style: .continuous))
                            }
                            .buttonStyle(.plain)
                        }
                    }
                  }
                  .padding(22)
                }
                .frame(maxWidth: min(480, UIScreen.main.bounds.width - 40))
                .frame(maxHeight: UIScreen.main.bounds.height * 0.80)
                .background(
                    Color(red: 22/255, green: 27/255, blue: 34/255).opacity(0.98),
                    in: RoundedRectangle(cornerRadius: 22, style: .continuous)
                )
                .overlay {
                    RoundedRectangle(cornerRadius: 22, style: .continuous)
                        .stroke(Color.white.opacity(0.10), lineWidth: 1)
                }
                .shadow(color: .black.opacity(0.5), radius: 32, x: 0, y: 8)
                .padding(.horizontal, 20)

                Spacer()
            }
        }
        .interactiveDismissDisabled(true)
    }
}

// MARK: - UserDefaults helper

extension AIBootDisclaimerView {
    /// Legacy boolean key from before version-keyed suppression. Read once for migration, then cleared.
    private static let legacyAcceptedKey = "aiDisclaimerAccepted_v1"
    /// Stores the "<version>-<build>" string for which the user chose "Don't show again".
    static let suppressedBuildKey = "aiDisclaimerSuppressedBuild_v2"

    /// True once the user tapped Got it during this launch.
    private static var acceptedThisLaunch = false

    static var currentBuildIdentifier: String {
        let info = Bundle.main.infoDictionary ?? [:]
        let version = info["CFBundleShortVersionString"] as? String ?? "0"
        let build = info["CFBundleVersion"] as? String ?? "0"
        return "\(version)-\(build)"
    }

    /// True when the disclaimer should NOT be shown right now.
    static var isAccepted: Bool {
        if acceptedThisLaunch { return true }
        let stored = UserDefaults.standard.string(forKey: suppressedBuildKey)
        return stored == currentBuildIdentifier
    }

    /// Call when the user taps Got it. Persists suppression for the current build only if requested.
    static func markAccepted(dontShowAgain: Bool) {
        acceptedThisLaunch = true
        let defaults = UserDefaults.standard
        if dontShowAgain {
            defaults.set(currentBuildIdentifier, forKey: suppressedBuildKey)
        } else {
            defaults.removeObject(forKey: suppressedBuildKey)
        }
        defaults.removeObject(forKey: legacyAcceptedKey)
    }
}
