import SwiftUI

/// Read-only view of the full AI disclaimer text, accessible from Settings → Legal.
/// Text mirrors AIBootDisclaimerView verbatim.
struct LegalView: View {
    @Environment(\.openURL) private var openURL

    var body: some View {
        ScrollView {
            VStack(alignment: .leading, spacing: 16) {
                Text("AI Disclaimer")
                    .font(.system(size: 27, weight: .heavy))
                    .foregroundStyle(SkimStyle.text)

                Group {
                    Text("Skim is a client. We do not develop, train, host, fine-tune, or operate any AI model. All AI output is generated by ")
                    + Text("third-party providers you connect using your own keys, subscription, or local install")
                        .bold()
                    + Text(" (Anthropic, OpenAI, OpenRouter, xAI, Ollama, Apple Foundation Models, llama.cpp, etc.). Skim does not run any backend; we collect no telemetry, no analytics, and no prompts or responses. Your requests go from your device directly to the provider you chose.")
                }
                .font(.system(size: 15, weight: .regular))
                .foregroundStyle(SkimStyle.text)
                .lineSpacing(4)
                .fixedSize(horizontal: false, vertical: true)

                Group {
                    Text("We do not produce, review, curate, audit, or endorse AI output. Output may be inaccurate, biased, offensive, harmful, fabricated, or otherwise objectionable. ")
                    + Text("You alone are responsible for your prompts, provider choice, and use of the output.")
                        .bold()
                    + Text(" Your relationship is with the provider and is governed by their terms and acceptable-use policy.")
                }
                .font(.system(size: 15, weight: .regular))
                .foregroundStyle(SkimStyle.text)
                .lineSpacing(4)
                .fixedSize(horizontal: false, vertical: true)

                Text("Skim is provided AS IS, without warranties of any kind. To the maximum extent permitted by law, Skim and its developer disclaim all liability for AI-generated content and any consequences of its use.")
                    .font(.system(size: 14, weight: .regular))
                    .foregroundStyle(SkimStyle.secondary)
                    .lineSpacing(4)
                    .fixedSize(horizontal: false, vertical: true)

                Divider()
                    .overlay(SkimStyle.separator)
                    .padding(.vertical, 4)

                HStack(spacing: 18) {
                    Button("Terms of Service") {
                        openURL(URL(string: "https://gm2211.github.io/skim/terms.html")!)
                    }
                    .font(.system(size: 15, weight: .semibold))
                    .foregroundStyle(SkimStyle.accent)
                    .buttonStyle(.plain)

                    Button("Privacy Policy") {
                        openURL(URL(string: "https://gm2211.github.io/skim/privacy.html")!)
                    }
                    .font(.system(size: 15, weight: .semibold))
                    .foregroundStyle(SkimStyle.accent)
                    .buttonStyle(.plain)
                }
            }
            .padding(.horizontal, 24)
            .padding(.top, 20)
            .padding(.bottom, 40)
        }
        .background(SkimStyle.background.ignoresSafeArea())
        .navigationTitle("Legal")
        .navigationBarTitleDisplayMode(.inline)
    }
}
