#!/usr/bin/env node
// A stand-in OpenAI-compatible model server for offline development.
//
// Every AI feature in Skim (summaries, triage, themes, catch-up, chat) goes
// through a provider, and the OpenAI-compatible provider backs openai, xai,
// openrouter, ollama and custom. Pointing one of those at this server exercises
// the real request shaping, the real JSON-mode parsing and the real error paths
// without a network or an API key.
//
//   node scripts/dev-llm.mjs        # http://127.0.0.1:4546/v1
//
// Then in Settings pick "Ollama" (or Custom) with that endpoint. Responses are
// derived from the prompt, not generated, so they are deterministic and
// obviously synthetic — good for testing, useless as journalism.
import { createServer } from "node:http";

const PORT = Number(process.env.DEV_LLM_PORT ?? 4546);

const MODELS = [
  "skim-dev-small",
  "skim-dev-large",
  "skim-dev-json",
];

/** Parses the "handle TAB title TAB [source] TAB excerpt" listing the app sends. */
function parseListing(text) {
  const rows = [];
  for (const line of text.split("\n")) {
    const parts = line.split("\t");
    if (parts.length < 3) continue;
    const id = Number(parts[0]);
    if (!Number.isInteger(id)) continue;
    rows.push({
      id,
      title: parts[1].trim(),
      source: (parts[2] || "").replace(/^\[|\]$/g, "").trim(),
      excerpt: (parts[3] || "").trim(),
    });
  }
  return rows;
}

const firstSentence = (text) =>
  (text.split(/(?<=\.)\s/)[0] || text).trim().slice(0, 240);

function topicOf(title) {
  const stop = new Set([
    "the", "a", "an", "of", "to", "in", "on", "for", "and", "with", "your",
    "why", "how", "is", "are", "at", "into", "over", "from", "by", "its",
  ]);
  return (
    title
      .toLowerCase()
      .replace(/[^a-z0-9\s]/g, " ")
      .split(/\s+/)
      .filter((w) => w.length > 3 && !stop.has(w))
      .slice(0, 3)
      .join(" ") || "this story"
  );
}

function themesFor(rows) {
  const buckets = new Map();
  for (const row of rows) {
    const key = topicOf(row.title).split(" ")[0] || "misc";
    if (!buckets.has(key)) buckets.set(key, []);
    buckets.get(key).push(row);
  }
  const themes = [...buckets.entries()].slice(0, 10).map(([key, items]) => ({
    label: key.replace(/^./, (c) => c.toUpperCase()) + " coverage",
    summary: `${items.length} item${items.length === 1 ? "" : "s"} on ${key}, led by ${items[0].source || "an unnamed source"}.`,
    articles: items.map((i, n) => ({ id: i.id, relevance: Math.max(0.4, 0.95 - n * 0.1) })),
  }));
  return JSON.stringify({ themes });
}

function triageFor(rows) {
  // Recent + long excerpt reads as substantive; short listicle titles read as noise.
  const triage = rows.map((row) => {
    let priority = 3;
    if (row.excerpt.length > 180) priority = 4;
    if (/probe|outage|breach|regulat|security|down/i.test(row.title)) priority = 5;
    if (/keyboard|laptop|deal|review/i.test(row.title)) priority = 2;
    return {
      id: row.id,
      priority,
      reason: `${topicOf(row.title)} — ${priority >= 4 ? "worth reading now" : "read when there is time"}.`,
    };
  });
  return JSON.stringify({ triage });
}

function catchupFor(rows) {
  const takeaways = rows.slice(0, 10).map((row) => ({
    text: `${row.title}.`,
    article_ids: [row.id],
  }));
  const notable_mentions = rows.slice(10, 18).map((row) => ({
    text: `${row.source || "A source"} also covered ${topicOf(row.title)}.`,
    article_ids: [row.id],
  }));
  return JSON.stringify({ takeaways, notable_mentions });
}

function summaryFor(userPrompt, wantBullets) {
  const title = (userPrompt.match(/Article title:\s*(.+)/) || [])[1] || "the article";
  const bodyMatch = userPrompt.match(/Article text:\s*([\s\S]+?)\n\n(?:Write|Respond)/);
  const body = (bodyMatch ? bodyMatch[1] : userPrompt).trim();
  const sentences = body
    .split(/(?<=\.)\s+/)
    .map((s) => s.trim())
    .filter((s) => s.length > 40);

  if (wantBullets) {
    const bullets = sentences.slice(0, 3).map((s) => s.slice(0, 180));
    return JSON.stringify({
      bullets: bullets.length ? bullets : [`${title.trim()}.`],
      notes: "Generated by the local dev model.",
    });
  }
  const summary =
    sentences.slice(0, 2).join(" ").slice(0, 700) || `${title.trim()}.`;
  return JSON.stringify({ summary, notes: "Generated by the local dev model." });
}

function chatReply(messages) {
  const question = [...messages].reverse().find((m) => m.role === "user")?.content ?? "";
  const context = messages
    .filter((m) => m.role !== "user")
    .map((m) => m.content)
    .join("\n");
  const source = context.length > question.length ? context : question;
  const lines = source
    .split("\n")
    .map((l) => l.trim())
    .filter((l) => l.length > 60);
  const asked = question.split("\n").filter((l) => l.trim()).pop() ?? "";

  if (!lines.length) {
    return `I don't have the article text here, so I can't answer "${asked.slice(0, 120)}" from the source.`;
  }
  return [
    `Short answer: ${firstSentence(lines[0])}`,
    "",
    lines.slice(1, 3).map((l) => `- ${firstSentence(l)}`).join("\n"),
    "",
    `(Answering "${asked.slice(0, 120)}" from the text above. This is the local dev model, so treat the wording as synthetic.)`,
  ]
    .filter(Boolean)
    .join("\n");
}

function respond(messages) {
  const user = [...messages].reverse().find((m) => m.role === "user")?.content ?? "";
  const all = messages.map((m) => m.content).join("\n");

  if (/"themes"\s*:/.test(user)) return themesFor(parseListing(user));
  if (/"triage"\s*:/.test(user)) return triageFor(parseListing(user));
  if (/"takeaways"\s*:/.test(user)) return catchupFor(parseListing(user));
  if (/"bullets"/.test(user)) return summaryFor(user, true);
  if (/"summary"/.test(user) && /"notes"/.test(all)) return summaryFor(user, false);
  return chatReply(messages);
}

const json = (res, status, body) => {
  res.writeHead(status, {
    "Content-Type": "application/json",
    "Access-Control-Allow-Origin": "*",
  });
  res.end(JSON.stringify(body));
};

createServer(async (req, res) => {
  let raw = "";
  for await (const chunk of req) raw += chunk;
  const path = new URL(req.url, `http://127.0.0.1:${PORT}`).pathname;

  if (path.endsWith("/models") || path === "/api/tags") {
    return json(res, 200, {
      object: "list",
      data: MODELS.map((id) => ({ id, object: "model", owned_by: "skim-dev" })),
      models: MODELS.map((name) => ({ name, model: name })),
    });
  }

  if (path.endsWith("/chat/completions")) {
    let body;
    try {
      body = JSON.parse(raw);
    } catch {
      return json(res, 400, { error: { message: "invalid JSON body" } });
    }
    const messages = (body.messages ?? []).map((m) => ({
      role: m.role,
      content:
        typeof m.content === "string"
          ? m.content
          : (m.content ?? [])
              .map((part) => part.text ?? "")
              .join("\n"),
    }));
    const content = respond(messages);
    console.log(
      `[dev-llm] ${body.model ?? "?"} json_mode=${!!body.response_format} -> ${content.slice(0, 70).replace(/\n/g, " ")}…`,
    );
    return json(res, 200, {
      id: `chatcmpl-dev-${Date.now()}`,
      object: "chat.completion",
      created: Math.floor(Date.now() / 1000),
      model: body.model ?? MODELS[0],
      choices: [
        { index: 0, message: { role: "assistant", content }, finish_reason: "stop" },
      ],
      usage: { prompt_tokens: 100, completion_tokens: 100, total_tokens: 200 },
    });
  }

  json(res, 404, { error: { message: `no route for ${path}` } });
}).listen(PORT, "127.0.0.1", () =>
  console.log(`dev-llm on http://127.0.0.1:${PORT}/v1 (${MODELS.join(", ")})`),
);
