#!/usr/bin/env python3
"""Regenerate the shared Unicode casefold table; requires Unicode 16.0 data."""
from pathlib import Path
import unicodedata

if unicodedata.unidata_version != "16.0.0":
    raise SystemExit("Use Python with Unicode 16.0.0 data to reproduce this table.")
rows = []
for point in range(128, 0x110000):
    if 0xD800 <= point <= 0xDFFF:
        continue
    character = chr(point)
    folded = character.casefold()
    if character == folded:
        continue
    scalars = [ord(character) for character in folded]
    assert 1 <= len(scalars) <= 3
    rows.append((point, *(scalars + [0] * (3 - len(scalars)))))
path = Path(__file__).resolve().parents[1] / "shared/SkimStoryPolicy/Sources/SkimStoryPolicy/SkimUnicodeCaseFold.h"
path.write_text(
    "/* Generated by scripts/generate-chat-casefold.py from Unicode 16.0.0.\n"
    " * Non-ASCII full casefold mappings; source bytes are never rewritten. */\n"
    "static const uint32_t evidence_casefold[][4] = {\n"
    + "".join("    { " + ", ".join(f"0x{point:X}" for point in row) + " },\n" for row in rows)
    + "};\n"
)

# Match complete Unicode letters, numbers and combining marks; punctuation,
# symbols and spacing always separate query/source words.
ranges = []
start = previous = None
for point in range(128, 0x110000):
    is_word = unicodedata.category(chr(point))[0] in "LNM"
    if is_word:
        if start is None:
            start = point
        previous = point
    elif start is not None:
        ranges.append((start, previous))
        start = previous = None
if start is not None:
    ranges.append((start, previous))
with path.open("a") as output:
    output.write("\nstatic const uint32_t evidence_word_ranges[][2] = {\n")
    output.writelines(f"    {{ 0x{start:X}, 0x{end:X} }},\n" for start, end in ranges)
    output.write("};\n")
