import { useEffect, useState } from "react";
import { createPortal } from "react-dom";

interface Props {
  onDismiss: () => void;
}

export function AIBootDisclaimer({ onDismiss }: Props) {
  const [mounted, setMounted] = useState(false);

  useEffect(() => {
    const id = window.setTimeout(() => setMounted(true), 30);
    return () => window.clearTimeout(id);
  }, []);

  return createPortal(
    <div
      className="fixed inset-0 z-[100] flex items-center justify-center"
      style={{
        background: "rgba(0,0,0,0.7)",
        backdropFilter: "blur(8px)",
        opacity: mounted ? 1 : 0,
        transition: "opacity 200ms ease-out",
        padding: "20px",
        paddingTop: "max(var(--sat, 0px), 60px)",
        paddingBottom: "max(var(--sab, 0px), 20px)",
      }}
      role="dialog"
      aria-modal="true"
      aria-labelledby="ai-disclaimer-title"
    >
      <div
        className="border border-white/10 rounded-2xl shadow-2xl flex flex-col"
        style={{
          background: "rgba(22, 27, 34, 0.98)",
          width: "min(480px, 100%)",
          maxHeight: "100%",
          overflow: "hidden",
        }}
      >
        <div style={{ padding: "20px 22px 8px" }}>
          <div
            className="flex items-center gap-2"
            style={{ marginBottom: 10 }}
          >
            <svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" className="text-accent">
              <path d="M12 2a4 4 0 0 1 4 4v1a2 2 0 0 1 2 2v1a4 4 0 0 1-2.5 3.7M12 2a4 4 0 0 0-4 4v1a2 2 0 0 0-2 2v1a4 4 0 0 0 2.5 3.7M12 2v4M8.5 14.7A4 4 0 0 0 12 22a4 4 0 0 0 3.5-7.3" />
              <circle cx="12" cy="14" r="1" />
            </svg>
            <h2
              id="ai-disclaimer-title"
              className="text-text-primary"
              style={{ fontSize: 16, fontWeight: 600 }}
            >
              About AI in Skim
            </h2>
          </div>
        </div>
        <div
          className="overflow-y-auto text-text-primary"
          style={{ padding: "0 22px 4px", fontSize: 13, lineHeight: 1.5 }}
        >
          <p style={{ marginBottom: 10 }}>
            Skim is a client. We do not develop, train, host, fine-tune, or
            operate any AI model. All AI output is generated by{" "}
            <strong>third-party providers you connect using your own keys,
            subscription, or local install</strong> (Anthropic, OpenAI,
            OpenRouter, xAI, Ollama, Apple Foundation Models, llama.cpp, etc.).
            Skim does not run any backend; we collect no telemetry, no
            analytics, and no prompts or responses. Your requests go from your
            device directly to the provider you chose.
          </p>
          <p style={{ marginBottom: 10 }}>
            We do not produce, review, curate, audit, or endorse AI output.
            Output may be inaccurate, biased, offensive, harmful, fabricated,
            or otherwise objectionable. <strong>You alone are responsible for
            your prompts, provider choice, and use of the output.</strong> Your
            relationship is with the provider and is governed by their terms
            and acceptable-use policy.
          </p>
          <p className="text-text-muted" style={{ marginBottom: 10, fontSize: 12 }}>
            Skim is provided AS IS, without warranties of any kind. To the
            maximum extent permitted by law, Skim and its developer disclaim
            all liability for AI-generated content and any consequences of its
            use.
          </p>
          <p style={{ marginBottom: 10 }}>
            By tapping Got it you accept the{" "}
            <a
              href="https://gm2211.github.io/skim/terms.html"
              target="_blank"
              rel="noreferrer"
              className="text-accent hover:underline"
            >
              Terms
            </a>
            {" and "}
            <a
              href="https://gm2211.github.io/skim/privacy.html"
              target="_blank"
              rel="noreferrer"
              className="text-accent hover:underline"
            >
              Privacy Policy
            </a>
            .
          </p>
        </div>
        <div
          className="flex-shrink-0 border-t border-white/5 flex justify-end"
          style={{ padding: "12px 16px" }}
        >
          <button
            onClick={onDismiss}
            className="bg-accent text-white rounded-xl hover:bg-accent-hover font-medium transition-colors"
            style={{ padding: "10px 18px", fontSize: 13 }}
            autoFocus
          >
            Got it
          </button>
        </div>
      </div>
    </div>,
    document.body
  );
}
